[project]
name = "webauthn-test-vectors"
description = "Scripts for generating WebAuthn test vectors"
requires-python = ">=3.10, <4"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
cryptography = "^44.0.2"
fido2 = "^1.2.0"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
